#
# R interface to the SAS mixed model simulator
# 
# Author: Sarah Kreidler
# Created: 8/14/2013
#
#

#
# Generate an SAS/IML string representation of an R matrix
#
matrixToIML <- function(name, m) {
  rowDataStr = paste(sapply(1:nrow(m),
                      function(i){paste("\t", paste(m[i,], collapse=" "), 
                                        ifelse(i<nrow(m),",",""))}),collapse="\n")
  imlStr = paste("\n",name, "= {\n", rowDataStr, "\n};\n\n")
  return(imlStr)
}

##
# Generate SAS code for mixed model simulation
#
# Arguments
# studyDesign - the study design object
# path - the path for the generated code
#
generateSASCode.mixedSimulation = function(studyDesign, path) {
  
  # define code at start of file
  header = paste("
/*
* !! GENERATED BY sasEmpiricalPower.R - DO NOT EDIT !!
*
* SAS code for simulating a linear mixed model
*
* Date: " , format(Sys.time(), "%a %b-%d-%Y"),
"\n* Study Design: ", name(studyDesign), 
"\n* Description: ", description(studyDesign),                  
"\n*/\n\n", sep="");
  
  # define the actual command to run the simulation
  command = paste("\n", sascall(studyDesign), "\n",
"\nproc iml;
%INCLUDE \"simulateMixedModel.sxs\"/NOSOURCE2;\n\n",
"call calculateEmpiricalPowerConditional(10000, 1000,  
                  simlib, simprefix, \"mixedCall\",
                  X, XModel, Beta, SigmaS,
                  empiricalPower);
",                  
    sep="")
  
  # closing statements
  footer = "\nQUIT;\n\n";
  
  imlCode = paste(
    header,
    matrixToIML("X", XMatrix(studyDesign)),
    matrixToIML("beta", betaMatrix(studyDesign)),
    matrixToIML("Sigma", SigmaMatrix(studyDesign)),
    matrixToIML("thetaNull", thetaNullMatrix(studyDesign)),
    matrixToIML("C", contrast(studyDesign)),
    command,
    footer,
    sep=""
    )
  return(imlCode);
  #write(imlCode, file=path)
}

#
#
#
# calculateEmpiricalPower
#
# Calculates empirical power for the given study design object.
# Executes a SAS macro from the command line to do so.
# Results are written to the specified data set
#
# Arguments:
# studyDesign - an object describing the study design matrices
# outputDatasetName - name of the output dataset
#
# Returns:
# None, but writes output dataset
#
# throws:
# simpleError on failure
#
calculateEmpiricalPower.mixed <- function(studyDesign, 
                                    outputDatasetName="empiricalPower") {
  filename = paste("generated_", gsub(" ", "", name(studyDesign)), ".sas", sep="")
  sascode = generateSASCode.mixedSimulation(studyDesign, paste(GEN_DIR,filename,sep="/"))
  # TODO: exec call to SAS
  # load data result
  # return empirical power value
  # TODO: handle iterations - maybe options object?
}

